### ISSUE TITLE
Question about Silo Deployment

### ISSUE THREAD

**Issue by normanhh3** [OrleansContrib/OrleansTemplates#6]
Just started looking into Orleans recently and came across these templates which look like a good starting point.

Is an intentional design goal of these templates to deploy the WebAPI alongside each silo instance?

Is the code in the [Program.cs](https://github.com/OrleansContrib/OrleansTemplates/blob/master/VSTemplates/ETG.Orleans.Templates.Host/Program.cs) template really designed to be production code?  It seems like it would be preferable to host the Orleans Silo and WebAPI using something like [Topshelf for Windows Service hosting](https://github.com/Topshelf/Topshelf)?

I'm looking for guidelines for implementation, thanks for clarification and pointers!

**Comment by nehmebilal** [comment]
Hi @normanhh3,

All what OrleansTemplates provides from that perspective is auto-generating the WebApi code for you. The hosting side is more Sample code than production code.

The WebApi doesn't need to be deployed alongside the Orleans silo. The WebApi communicates with the Orleans Silo using the Orleans client which is initialized as follows (and as shown in  [Program.cs](https://github.com/OrleansContrib/OrleansTemplates/blob/master/VSTemplates/ETG.Orleans.Templates.Host/Program.cs)):

```csharp
Orleans.GrainClient.Initialize("DevTestClientConfiguration.xml");
```

I am not sure if anyone has used the code in production yet. For deployment, you can use [Yams] (https://github.com/Microsoft/yams) or Service Fabric, cloud services or ARM. I'm sure Orleans documentation also has some information about deployments.

**Comment by normanhh3** [comment]
Thanks for the feedback.  My scenario is an on-premise deployment so I'm a little more limited in the tooling I can use.  Thanks for your response.
