### ISSUE TITLE
Recommend removing this repository

### ISSUE THREAD

**Issue by creyke** [OrleansContrib/OrleansTemplates#7]
This repository is confusing developers as it doesn't support VS 2017.

Templates are now officially provided from the dotnet repo.

Any objections @nehmebilal ?

**Comment by galvesribeiro** [comment]
I agree with you.

I have an outstanding PR https://github.com/dotnet/orleans/pull/3018 that adds a .Net CLI project template which support VS 2017 already in place.

**Comment by nehmebilal** [comment]
No objections! I have no time to maintain it.

**Comment by galvesribeiro** [comment]
Lets leave a note on main README saying that we will deprecate this repo in 30 days.

**Comment by nehmebilal** [comment]
Are you planing to delete the repo or just mark it as obselete? Deleting repos means loose the code and history which is probably something to avoid (I know I can fork it).

**Comment by galvesribeiro** [comment]
No no, just lock and deprecate it.

**Comment by nehmebilal** [comment]
Is the following at the top of the README good enough?

***IMPORTANT NOTE: This repo is NOT up-to-date with the latest version of Orleans and is not being maintained.***

**Comment by galvesribeiro** [comment]
Perfect! Just add that as a header and lock the repo and we should be fine

**Comment by nehmebilal** [comment]
How you you lock a repo and what does that do? 😄

**Comment by galvesribeiro** [comment]
I've made it read-only to everyone. It should be OK :)

**Comment by galvesribeiro** [comment]
And also made the note a bit bigger ;)

**Comment by nehmebilal** [comment]
Haha looks good :)
